ALTER TABLE IBP_RETRY_CONFIGURATION
 DROP PRIMARY KEY CASCADE;

DROP TABLE IBP_RETRY_CONFIGURATION CASCADE CONSTRAINTS;

CREATE TABLE IBP_RETRY_CONFIGURATION
(
  APPLICATION_NAME      VARCHAR2(4 BYTE),
  MAX_RETRY_NUMBER      NUMBER                  NOT NULL,
  RETRY_WAITING_PERIOD  NUMBER                  NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX IBP_RETRY_CONFIGURATION_PK ON IBP_RETRY_CONFIGURATION
(APPLICATION_NAME)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE IBP_RETRY_CONFIGURATION ADD (
  CONSTRAINT IBP_RETRY_CONFIGURATION_PK
 PRIMARY KEY
 (APPLICATION_NAME)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
