--1.Create sequence for IBP Tables

 
Prompt drop Sequence IBP_PROVCON_LINK;
DROP SEQUENCE IBP_PROVCON_LINK
/

Prompt Sequence IBP_PROVCON_LINK;
--
-- IBP_PROVCON_LINK  (Sequence) 
--
CREATE SEQUENCE IBP_PROVCON_LINK START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER
/



Prompt drop Sequence IBP_STAGING_SEQ;
DROP SEQUENCE IBP_STAGING_SEQ
/

Prompt Sequence IBP_STAGING_SEQ;
--
-- IBP_STAGING_SEQ  (Sequence) 
--
CREATE SEQUENCE IBP_STAGING_SEQ START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 28 NOORDER
/



Prompt drop Sequence IBP_ORDERLINE_MBC_SEQUENCE;
DROP SEQUENCE IBP_ORDERLINE_MBC_SEQUENCE
/

Prompt Sequence IBP_ORDERLINE_MBC_SEQUENCE;
--
-- IBP_ORDERLINE_MBC_SEQUENCE  (Sequence) 
--
CREATE SEQUENCE IBP_ORDERLINE_MBC_SEQUENCE START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 28 NOORDER
/



Prompt drop Sequence IBP_ORDERLINE_MZ_SEQ;
DROP SEQUENCE IBP_ORDERLINE_MZ_SEQ
/

Prompt Sequence IBP_ORDERLINE_MZ_SEQ;
--
-- IBP_ORDERLINE_MZ_SEQ  (Sequence) 
--
CREATE SEQUENCE IBP_ORDERLINE_MZ_SEQ START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 28 NOORDER
/



Prompt drop Sequence IBP_PROCESSING_SEQ;
DROP SEQUENCE IBP_PROCESSING_SEQ
/

Prompt Sequence IBP_PROCESSING_SEQ;
--
-- IBP_PROCESSING_SEQ  (Sequence) 
--
CREATE SEQUENCE IBP_PROCESSING_SEQ START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 28 NOORDER
/



Prompt drop Sequence IBP_ORDERLINE_PCRF_SEQ;
DROP SEQUENCE IBP_ORDERLINE_PCRF_SEQ
/

Prompt Sequence IBP_ORDERLINE_PCRF_SEQ;
--
-- IBP_ORDERLINE_PCRF_SEQ  (Sequence) 
--
CREATE SEQUENCE IBP_ORDERLINE_PCRF_SEQ START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 28 NOORDER
/




-- DROPPING TABLES;



Prompt drop TABLE IBP_BSCS_ACTIONS;
ALTER TABLE IBP_BSCS_ACTIONS
 DROP PRIMARY KEY CASCADE
/

DROP TABLE IBP_BSCS_ACTIONS CASCADE CONSTRAINTS
/
Prompt drop TABLE IBP_BILLCYCLEVSPAMSERVICE;
ALTER TABLE IBP_BILLCYCLEVSPAMSERVICE
 DROP PRIMARY KEY CASCADE
/

DROP TABLE IBP_BILLCYCLEVSPAMSERVICE CASCADE CONSTRAINTS
/

Prompt drop TABLE IBP_CONFIG_TAB;
DROP TABLE IBP_CONFIG_TAB CASCADE CONSTRAINTS
/

Prompt drop TABLE IBP_PARAMETER_TRANSLATION;
DROP TABLE IBP_PARAMETER_TRANSLATION CASCADE CONSTRAINTS
/

Prompt drop TABLE IBP_PRODUCT_TYPE_DEFINITION;
ALTER TABLE IBP_PRODUCT_TYPE_DEFINITION
 DROP PRIMARY KEY CASCADE
/

DROP TABLE IBP_PRODUCT_TYPE_DEFINITION CASCADE CONSTRAINTS
/

Prompt drop TABLE IBP_PRODUCT_CONFIGURATION;
ALTER TABLE IBP_PRODUCT_CONFIGURATION
 DROP PRIMARY KEY CASCADE
/

DROP TABLE IBP_PRODUCT_CONFIGURATION CASCADE CONSTRAINTS
/


Prompt drop TABLE IBP_PROVIDER_CONSUMER_LINK;
ALTER TABLE IBP_PROVIDER_CONSUMER_LINK
 DROP PRIMARY KEY CASCADE
/

DROP TABLE IBP_PROVIDER_CONSUMER_LINK CASCADE CONSTRAINTS
/

Prompt drop TABLE IBP_RETRY_CONFIGURATION;
ALTER TABLE IBP_RETRY_CONFIGURATION
 DROP PRIMARY KEY CASCADE
/

DROP TABLE IBP_RETRY_CONFIGURATION CASCADE CONSTRAINTS
/


Prompt drop TABLE IBP_WORKFLOW_DEFINITION;
DROP TABLE IBP_WORKFLOW_DEFINITION CASCADE CONSTRAINTS
/

Prompt drop TABLE IBP_WORKFLOW_CONFIGURATION;
DROP TABLE IBP_WORKFLOW_CONFIGURATION CASCADE CONSTRAINTS
/       

Prompt drop TABLE IBP_STAGING;
ALTER TABLE IBP_STAGING
 DROP PRIMARY KEY CASCADE
/

DROP TABLE IBP_STAGING CASCADE CONSTRAINTS
/
       

Prompt drop TABLE IBP_PROCESSING_QUEUE;
ALTER TABLE IBP_PROCESSING_QUEUE
 DROP PRIMARY KEY CASCADE
/

DROP TABLE IBP_PROCESSING_QUEUE CASCADE CONSTRAINTS
/

Prompt drop TABLE IBP_ORDERLINE_PCRF;
ALTER TABLE IBP_ORDERLINE_PCRF
 DROP PRIMARY KEY CASCADE
/

DROP TABLE IBP_ORDERLINE_PCRF CASCADE CONSTRAINTS
/


Prompt drop TABLE IBP_ORDERLINE_MZ;
ALTER TABLE IBP_ORDERLINE_MZ
 DROP PRIMARY KEY CASCADE
/

DROP TABLE IBP_ORDERLINE_MZ CASCADE CONSTRAINTS
/
Prompt drop TABLE IBP_ORDERLINE_MBC;
ALTER TABLE IBP_ORDERLINE_MBC
 DROP PRIMARY KEY CASCADE
/

DROP TABLE IBP_ORDERLINE_MBC CASCADE CONSTRAINTS
/
 

Prompt Table IBP_BSCS_ACTIONS;
--
-- IBP_BSCS_ACTIONS  (Table) 
--
CREATE TABLE IBP_BSCS_ACTIONS ( ACTION_ID NUMBER NOT NULL, BSCS_ACTION_NAME VARCHAR2(50 CHAR) NOT NULL ) TABLESPACE DATA PCTUSED 0 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL NOMONITORING
/

COMMENT ON TABLE IBP_BSCS_ACTIONS IS 'The table will be used to configure different BSCS events in IBP'
/

COMMENT ON COLUMN IBP_BSCS_ACTIONS.ACTION_ID IS 'Primary Key - Unique action_ids'
/

COMMENT ON COLUMN IBP_BSCS_ACTIONS.BSCS_ACTION_NAME IS 'Action Names '
/


Prompt Index IBP_BSCS_ACTIONS_PK;
--
-- IBP_BSCS_ACTIONS_PK  (Index) 
--
--  Dependencies: 
--   IBP_BSCS_ACTIONS (Table)
--
CREATE UNIQUE INDEX IBP_BSCS_ACTIONS_PK ON IBP_BSCS_ACTIONS (ACTION_ID) LOGGING TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table IBP_BSCS_ACTIONS 
-- 
Prompt Non-Foreign Key Constraints on Table IBP_BSCS_ACTIONS;
ALTER TABLE IBP_BSCS_ACTIONS ADD (  CONSTRAINT IBP_BSCS_ACTIONS_PK PRIMARY KEY (ACTION_ID) USING INDEX TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ))
/




Prompt Table IBP_BILLCYCLEVSPAMSERVICE;
--
-- IBP_BILLCYCLEVSPAMSERVICE  (Table) 
--
CREATE TABLE IBP_BILLCYCLEVSPAMSERVICE ( IBP_BILL_CYCLE_VS_PAM_SERV_ID NUMBER NOT NULL, BILL_CYCLE NUMBER NOT NULL, PAM_SERVICE_ID NUMBER NOT NULL, PAM_CLASS_ID NUMBER NOT NULL, SCHEDULE_ID NUMBER NOT NULL, PRORATION CHAR(1 CHAR) NOT NULL ) TABLESPACE DATA PCTUSED 0 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL NOMONITORING
/

COMMENT ON TABLE IBP_BILLCYCLEVSPAMSERVICE IS 'Table to map a BSCS bill cycle to a PAM service'
/

COMMENT ON COLUMN IBP_BILLCYCLEVSPAMSERVICE.IBP_BILL_CYCLE_VS_PAM_SERV_ID IS 'Primary Key'
/

COMMENT ON COLUMN IBP_BILLCYCLEVSPAMSERVICE.BILL_CYCLE IS 'Bill cycle'
/

COMMENT ON COLUMN IBP_BILLCYCLEVSPAMSERVICE.PAM_SERVICE_ID IS 'Service ID for bill cycle'
/

COMMENT ON COLUMN IBP_BILLCYCLEVSPAMSERVICE.PAM_CLASS_ID IS 'class ID'
/

COMMENT ON COLUMN IBP_BILLCYCLEVSPAMSERVICE.SCHEDULE_ID IS 'Schedule Id'
/

COMMENT ON COLUMN IBP_BILLCYCLEVSPAMSERVICE.PRORATION IS 'Y/N values to indicate proration'
/


-- 
-- Non Foreign Key Constraints for Table IBP_BILLCYCLEVSPAMSERVICE 
-- 
Prompt Non-Foreign Key Constraints on Table IBP_BILLCYCLEVSPAMSERVICE;
ALTER TABLE IBP_BILLCYCLEVSPAMSERVICE ADD (  CONSTRAINT CHECK_PRORATION_VAL CHECK (PRORATION in ( 'Y', 'N')),  PRIMARY KEY (IBP_BILL_CYCLE_VS_PAM_SERV_ID) USING INDEX TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ))
/



Prompt Table IBP_CONFIG_TAB;
--
-- IBP_CONFIG_TAB  (Table) 
--
CREATE TABLE IBP_CONFIG_TAB ( NO_OF_ROWS NUMBER DEFAULT NULL NOT NULL ) TABLESPACE DATA PCTUSED 0 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL NOMONITORING
/

COMMENT ON TABLE IBP_CONFIG_TAB IS 'Table for configuring number of rows fetched by the procedure from ORDERLINE tables'
/

COMMENT ON COLUMN IBP_CONFIG_TAB.NO_OF_ROWS IS 'The number of rows fetched from ORDERLINE tables by IBP procedure. '
/


-- 
-- Non Foreign Key Constraints for Table IBP_CONFIG_TAB 
-- 
Prompt Non-Foreign Key Constraints on Table IBP_CONFIG_TAB;
ALTER TABLE IBP_CONFIG_TAB ADD (  CONSTRAINT CHECK_NO_OF_ROW_VAL CHECK (NO_OF_ROWS <> 0))
/



Prompt Table IBP_PARAMETER_TRANSLATION;
--
-- IBP_PARAMETER_TRANSLATION  (Table) 
--
CREATE TABLE IBP_PARAMETER_TRANSLATION ( PARAMETER_ENCODING VARCHAR2(40 CHAR), DECODED_VALUE NUMBER, THRESHOLD_ID NUMBER, EVENT_TYPE VARCHAR2(4 CHAR), MONETARY_AMT NUMBER, TMCODE VARCHAR2(5 CHAR), SNCODE NUMBER, IBP_ACTION NUMBER, COMMENTS VARCHAR2(2000 CHAR) ) TABLESPACE DATA PCTUSED 0 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL NOMONITORING
/

COMMENT ON TABLE IBP_PARAMETER_TRANSLATION IS 'Table for mapping BSCS parameter ID with the actual values which need to be sent to MBC/PCRF/MZ'
/

COMMENT ON COLUMN IBP_PARAMETER_TRANSLATION.PARAMETER_ENCODING IS 'The parameter which is passed with the service'
/

COMMENT ON COLUMN IBP_PARAMETER_TRANSLATION.DECODED_VALUE IS 'Decoded value'
/

COMMENT ON COLUMN IBP_PARAMETER_TRANSLATION.THRESHOLD_ID IS 'Threshold blocking MBC limit'
/

COMMENT ON COLUMN IBP_PARAMETER_TRANSLATION.EVENT_TYPE IS 'NE name'
/

COMMENT ON COLUMN IBP_PARAMETER_TRANSLATION.MONETARY_AMT IS 'Monetory value sent to MBC'
/

COMMENT ON COLUMN IBP_PARAMETER_TRANSLATION.TMCODE IS 'Tmcode of BSCS'
/

COMMENT ON COLUMN IBP_PARAMETER_TRANSLATION.SNCODE IS 'SNCODE of BSCS'
/

COMMENT ON COLUMN IBP_PARAMETER_TRANSLATION.IBP_ACTION IS 'IBP action e.g. 1. Roaming limit change 2. Profile update'
/

COMMENT ON COLUMN IBP_PARAMETER_TRANSLATION.COMMENTS IS 'Remarks'
/


-- 
-- Non Foreign Key Constraints for Table IBP_PARAMETER_TRANSLATION 
-- 
Prompt Non-Foreign Key Constraints on Table IBP_PARAMETER_TRANSLATION;
ALTER TABLE IBP_PARAMETER_TRANSLATION ADD (  CONSTRAINT CHECK_IBP_ACTION CHECK (IBP_ACTION IN( 1, 2 )))
/


Prompt Table IBP_PRODUCT_TYPE_DEFINITION;
--
-- IBP_PRODUCT_TYPE_DEFINITION  (Table) 
--
CREATE TABLE IBP_PRODUCT_TYPE_DEFINITION ( PRODUCT_TYPE_ID NUMBER NOT NULL, PRODUCT_TYPE VARCHAR2(2000 CHAR) NOT NULL, PARAMETER_TRANSLATION CHAR(1 CHAR) ) TABLESPACE DATA PCTUSED 0 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL NOMONITORING
/

COMMENT ON TABLE IBP_PRODUCT_TYPE_DEFINITION IS 'The table defines different business products for MBC  '
/

COMMENT ON COLUMN IBP_PRODUCT_TYPE_DEFINITION.PRODUCT_TYPE_ID IS 'Unique Product ID, Primary Key'
/

COMMENT ON COLUMN IBP_PRODUCT_TYPE_DEFINITION.PRODUCT_TYPE IS 'Type of product'
/

COMMENT ON COLUMN IBP_PRODUCT_TYPE_DEFINITION.PARAMETER_TRANSLATION IS 'Y/N values to indicate if there is associated Paramaters to be translated'
/


-- 
-- Non Foreign Key Constraints for Table IBP_PRODUCT_TYPE_DEFINITION 
-- 
Prompt Non-Foreign Key Constraints on Table IBP_PRODUCT_TYPE_DEFINITION;
ALTER TABLE IBP_PRODUCT_TYPE_DEFINITION ADD (  CONSTRAINT CHECK_PARAM_TRANS_VAL CHECK (PARAMETER_TRANSLATION IN ('Y', 'N')),  PRIMARY KEY (PRODUCT_TYPE_ID) USING INDEX TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ))
/


Prompt Table IBP_PRODUCT_CONFIGURATION;
--
-- IBP_PRODUCT_CONFIGURATION  (Table) 
--
--  Dependencies: 
--   IBP_PRODUCT_TYPE_DEFINITION (Table)
--
CREATE TABLE IBP_PRODUCT_CONFIGURATION ( PRODUCT_CONFIG_ID NUMBER, SHARED_ACCOUNT_OFFER_ID NUMBER, OFFER_TYPE NUMBER, PRODUCT_NAME VARCHAR2(2000 CHAR), TMCODE VARCHAR2(5 CHAR), SNCODE VARCHAR2(5 CHAR), PRODUCT_TYPE NUMBER, CONSUMING_TARIFF VARCHAR2(2000 CHAR), CONSUMING_SN VARCHAR2(2000 CHAR), DEFAULT_QOS VARCHAR2(2000 CHAR), UNTHROTTLE_QOS_LIST VARCHAR2(2000 CHAR), SERVICE_CLASS NUMBER, MZ_PROFILE VARCHAR2(256 CHAR), MZ_ROLE VARCHAR2(256 CHAR), PRORATED CHAR(1 CHAR), DEFAULT_PRODUCT CHAR(1 CHAR), REFILL_SHARED_ACCOUNT_OFFER_ID VARCHAR2(2000 CHAR) ) TABLESPACE DATA PCTUSED 0 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL NOMONITORING
/

COMMENT ON TABLE IBP_PRODUCT_CONFIGURATION IS 'The table is used to configure BSCS TM code and SN code for a MBC offer '
/

COMMENT ON COLUMN IBP_PRODUCT_CONFIGURATION.PRORATED IS 'To indicate if the offer is prorated. values in Y or N'
/

COMMENT ON COLUMN IBP_PRODUCT_CONFIGURATION.DEFAULT_PRODUCT IS 'Indicates if Default MBC service is associated. Values in Y/N'
/

COMMENT ON COLUMN IBP_PRODUCT_CONFIGURATION.REFILL_SHARED_ACCOUNT_OFFER_ID IS 'Refill offer id needed to set the balance after PAM run'
/

COMMENT ON COLUMN IBP_PRODUCT_CONFIGURATION.PRODUCT_CONFIG_ID IS 'Primary Key'
/

COMMENT ON COLUMN IBP_PRODUCT_CONFIGURATION.SHARED_ACCOUNT_OFFER_ID IS 'Offer Id of the provider configured in MBC'
/

COMMENT ON COLUMN IBP_PRODUCT_CONFIGURATION.OFFER_TYPE IS 'To check if the offer is REFILL = 1 or BASE = 0'
/

COMMENT ON COLUMN IBP_PRODUCT_CONFIGURATION.PRODUCT_NAME IS 'Business name of the product'
/

COMMENT ON COLUMN IBP_PRODUCT_CONFIGURATION.TMCODE IS 'TMCODE to check for the base product along with SNCODE combination'
/

COMMENT ON COLUMN IBP_PRODUCT_CONFIGURATION.SNCODE IS 'SNCODE'
/

COMMENT ON COLUMN IBP_PRODUCT_CONFIGURATION.PRODUCT_TYPE IS 'Product type definition [ reference to IBP_PRODUCT_TYPE_DEFINITION.PRODUCT_TYPE_ID ]'
/

COMMENT ON COLUMN IBP_PRODUCT_CONFIGURATION.CONSUMING_TARIFF IS 'TMCODEs used to configure the  partially shared implicit products separated by :'
/

COMMENT ON COLUMN IBP_PRODUCT_CONFIGURATION.CONSUMING_SN IS 'SNCODEs used to configure the sum and share products separated :'
/

COMMENT ON COLUMN IBP_PRODUCT_CONFIGURATION.DEFAULT_QOS IS 'Default QOS for an offer.'
/

COMMENT ON COLUMN IBP_PRODUCT_CONFIGURATION.UNTHROTTLE_QOS_LIST IS 'List of all the un-throttling profile ID for an offer separated by ¿;¿.'
/

COMMENT ON COLUMN IBP_PRODUCT_CONFIGURATION.SERVICE_CLASS IS 'The service class linked to the offer id'
/

COMMENT ON COLUMN IBP_PRODUCT_CONFIGURATION.MZ_PROFILE IS 'The Profile of the consumer sent to MZ'
/

COMMENT ON COLUMN IBP_PRODUCT_CONFIGURATION.MZ_ROLE IS 'MZ Role'
/


-- 
-- Non Foreign Key Constraints for Table IBP_PRODUCT_CONFIGURATION 
-- 
Prompt Non-Foreign Key Constraints on Table IBP_PRODUCT_CONFIGURATION;
ALTER TABLE IBP_PRODUCT_CONFIGURATION ADD (  CONSTRAINT CHECK_PRORATED_VAL CHECK (PRORATED IN ('Y', 'N')),  CONSTRAINT CHECK_DEFAULT_PROD_VAL CHECK (DEFAULT_PRODUCT IN ('Y', 'N')),  PRIMARY KEY (PRODUCT_CONFIG_ID) USING INDEX TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ))
/

-- 
-- Foreign Key Constraints for Table IBP_PRODUCT_CONFIGURATION 
-- 
Prompt Foreign Key Constraints on Table IBP_PRODUCT_CONFIGURATION;
ALTER TABLE IBP_PRODUCT_CONFIGURATION ADD (  FOREIGN KEY (PRODUCT_TYPE) REFERENCES IBP_PRODUCT_TYPE_DEFINITION (PRODUCT_TYPE_ID) ON DELETE CASCADE)
/



Prompt Table IBP_PROVIDER_CONSUMER_LINK;
--
-- IBP_PROVIDER_CONSUMER_LINK  (Table) 
--
CREATE TABLE IBP_PROVIDER_CONSUMER_LINK ( IBP_PROVIDER_CONSUMER_ID NUMBER, CUSTOMER_ID NUMBER NOT NULL, COID NUMBER NOT NULL, SHARED_ACCOUNT_OFFER_ID NUMBER, PROVIDER_MSISDN NUMBER, PROVIDER_ACCOUNT_OFFER_ID NUMBER, CONSUMER_MSISDN NUMBER ) TABLESPACE DATA PCTUSED 0 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL NOMONITORING
/

COMMENT ON TABLE IBP_PROVIDER_CONSUMER_LINK IS 'Table for maintaining provider consumer link for an offer id'
/

COMMENT ON COLUMN IBP_PROVIDER_CONSUMER_LINK.IBP_PROVIDER_CONSUMER_ID IS 'Primary Key'
/

COMMENT ON COLUMN IBP_PROVIDER_CONSUMER_LINK.CUSTOMER_ID IS 'Customer ID from BSCS'
/

COMMENT ON COLUMN IBP_PROVIDER_CONSUMER_LINK.COID IS 'BSCS Contract ID'
/

COMMENT ON COLUMN IBP_PROVIDER_CONSUMER_LINK.SHARED_ACCOUNT_OFFER_ID IS 'Offer id : commercial offer Id'
/

COMMENT ON COLUMN IBP_PROVIDER_CONSUMER_LINK.PROVIDER_MSISDN IS 'MSISDN of the provider contract'
/

COMMENT ON COLUMN IBP_PROVIDER_CONSUMER_LINK.PROVIDER_ACCOUNT_OFFER_ID IS 'Provider offer id'
/

COMMENT ON COLUMN IBP_PROVIDER_CONSUMER_LINK.CONSUMER_MSISDN IS 'MSISDN of the consuming contract'
/


Prompt Index CUSTOMER_ID_IND;
--
-- CUSTOMER_ID_IND  (Index) 
--
--  Dependencies: 
--   IBP_PROVIDER_CONSUMER_LINK (Table)
--
CREATE INDEX CUSTOMER_ID_IND ON IBP_PROVIDER_CONSUMER_LINK (CUSTOMER_ID) LOGGING TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table IBP_PROVIDER_CONSUMER_LINK 
-- 
Prompt Non-Foreign Key Constraints on Table IBP_PROVIDER_CONSUMER_LINK;
ALTER TABLE IBP_PROVIDER_CONSUMER_LINK ADD (  PRIMARY KEY (IBP_PROVIDER_CONSUMER_ID) USING INDEX TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ))
/


Prompt Table IBP_RETRY_CONFIGURATION;
--
-- IBP_RETRY_CONFIGURATION  (Table) 
--
CREATE TABLE IBP_RETRY_CONFIGURATION ( APPLICATION_NAME VARCHAR2(4 CHAR), MAX_RETRY_NUMBER NUMBER NOT NULL, RETRY_WAITING_PERIOD NUMBER NOT NULL ) TABLESPACE DATA PCTUSED 0 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL NOMONITORING
/
COMMENT ON TABLE IBP_RETRY_CONFIGURATION IS 'Table containing retry configuration for NEs'
/

COMMENT ON COLUMN IBP_RETRY_CONFIGURATION.APPLICATION_NAME IS 'Application Name [ MZ, MBC, PCRF]'
/

COMMENT ON COLUMN IBP_RETRY_CONFIGURATION.MAX_RETRY_NUMBER IS 'Maximum number of retries'
/

COMMENT ON COLUMN IBP_RETRY_CONFIGURATION.RETRY_WAITING_PERIOD IS 'Waiting period after which the retry will be done'
/


Prompt Index IBP_RETRY_CONFIGURATION_PK;
--
-- IBP_RETRY_CONFIGURATION_PK  (Index) 
--
--  Dependencies: 
--   IBP_RETRY_CONFIGURATION (Table)
--
CREATE UNIQUE INDEX IBP_RETRY_CONFIGURATION_PK ON IBP_RETRY_CONFIGURATION (APPLICATION_NAME) LOGGING TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table IBP_RETRY_CONFIGURATION 
-- 
Prompt Non-Foreign Key Constraints on Table IBP_RETRY_CONFIGURATION;
ALTER TABLE IBP_RETRY_CONFIGURATION ADD (  CONSTRAINT CHECK_RETRY_WAITING_PERIOD CHECK (RETRY_WAITING_PERIOD >= 0),  CONSTRAINT CHECK_RETRY_NUMBER CHECK (MAX_RETRY_NUMBER > 0),  CONSTRAINT CHECK_APPLICATION_NAME CHECK (APPLICATION_NAME IN ('MBC', 'MZ', 'PCRF')),  CONSTRAINT IBP_RETRY_CONFIGURATION_PK PRIMARY KEY (APPLICATION_NAME) USING INDEX TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ))
/



Prompt Table IBP_WORKFLOW_DEFINITION;
--
-- IBP_WORKFLOW_DEFINITION  (Table) 
--
CREATE TABLE IBP_WORKFLOW_DEFINITION ( SEQ NUMBER NOT NULL, APPLICATION_NAME VARCHAR2(4 CHAR), WORKFLOW_ID NUMBER NOT NULL, NE_ACTIONS VARCHAR2(2000 CHAR) ) TABLESPACE DATA PCTUSED 0 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL NOMONITORING
/

COMMENT ON TABLE IBP_WORKFLOW_DEFINITION IS 'Table for workflow definition'
/

COMMENT ON COLUMN IBP_WORKFLOW_DEFINITION.SEQ IS 'Sequence number'
/

COMMENT ON COLUMN IBP_WORKFLOW_DEFINITION.APPLICATION_NAME IS 'Network element name'
/

COMMENT ON COLUMN IBP_WORKFLOW_DEFINITION.WORKFLOW_ID IS 'Workflow Id of the application'
/

COMMENT ON COLUMN IBP_WORKFLOW_DEFINITION.NE_ACTIONS IS 'command name to be executed on NE'
/


-- 
-- Non Foreign Key Constraints for Table IBP_WORKFLOW_DEFINITION 
-- 
Prompt Non-Foreign Key Constraints on Table IBP_WORKFLOW_DEFINITION;
ALTER TABLE IBP_WORKFLOW_DEFINITION ADD (  CONSTRAINT CHECK_APP_NAME_VAL CHECK (APPLICATION_NAME IN ( 'MBC', 'PCRF', 'MZ' )),  CONSTRAINT CHECK_WORKFLOW_ID CHECK (WORKFLOW_ID > 0))
/



Prompt Table IBP_WORKFLOW_CONFIGURATION;
--
-- IBP_WORKFLOW_CONFIGURATION  (Table) 
--
--  Dependencies: 
--   IBP_PRODUCT_TYPE_DEFINITION (Table)
--   IBP_BSCS_ACTIONS (Table)
--
CREATE TABLE IBP_WORKFLOW_CONFIGURATION ( ACTION_ID NUMBER NOT NULL, PRODUCT_TYPE_ID NUMBER, MBC_WORKFLOW_ID NUMBER, MZ_WORKFLOW_ID NUMBER, PCRF_WORKFLOW_ID NUMBER ) TABLESPACE DATA PCTUSED 0 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL NOMONITORING
/

COMMENT ON TABLE IBP_WORKFLOW_CONFIGURATION IS 'Table for configuring work flow management for different network elements (MBC,PCRF,MZ)'
/

COMMENT ON COLUMN IBP_WORKFLOW_CONFIGURATION.ACTION_ID IS 'IBP action id'
/

COMMENT ON COLUMN IBP_WORKFLOW_CONFIGURATION.PRODUCT_TYPE_ID IS 'Product type id'
/

COMMENT ON COLUMN IBP_WORKFLOW_CONFIGURATION.MBC_WORKFLOW_ID IS 'MBC workflow id'
/

COMMENT ON COLUMN IBP_WORKFLOW_CONFIGURATION.MZ_WORKFLOW_ID IS 'MZ workflow Id'
/

COMMENT ON COLUMN IBP_WORKFLOW_CONFIGURATION.PCRF_WORKFLOW_ID IS 'PCRF workflow id'
/

-- 
-- Foreign Key Constraints for Table IBP_WORKFLOW_CONFIGURATION 
-- 
Prompt Foreign Key Constraints on Table IBP_WORKFLOW_CONFIGURATION;
ALTER TABLE IBP_WORKFLOW_CONFIGURATION ADD (  FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES IBP_PRODUCT_TYPE_DEFINITION (PRODUCT_TYPE_ID) ON DELETE CASCADE,  FOREIGN KEY (ACTION_ID) REFERENCES IBP_BSCS_ACTIONS (ACTION_ID) ON DELETE CASCADE)
/


Prompt Table IBP_STAGING;
--
-- IBP_STAGING  (Table) 
--
--  Dependencies: 
--   IBP_BSCS_ACTIONS (Table)
--
CREATE TABLE IBP_STAGING ( TIMESTAMP DATE, REQ_ID INTEGER NOT NULL, CO_ID NUMBER, CUSTOMER_ID NUMBER, SEQ NUMBER, TMCODE NUMBER, SNCODE NUMBER, OLD_VAL VARCHAR2(2000 CHAR), NEW_VAL VARCHAR2(2000 CHAR), ACTION_ID NUMBER, REQUEST_STATUS CHAR(10 CHAR), BILLCYCLE NUMBER, CS_PARAM1 VARCHAR2(255 CHAR), CH_REASON NUMBER ) TABLESPACE DATA PCTUSED 0 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL NOMONITORING
/

COMMENT ON TABLE IBP_STAGING IS 'The table will be used as a intermediate table which will be populated by the triggers in BSCS table'
/

COMMENT ON COLUMN IBP_STAGING.REQUEST_STATUS IS 'Request status updated by IBP procedures or IBP core processor'
/

COMMENT ON COLUMN IBP_STAGING.BILLCYCLE IS 'BSCS billcycle of request'
/

COMMENT ON COLUMN IBP_STAGING.CS_PARAM1 IS 'Service parameter'
/

COMMENT ON COLUMN IBP_STAGING.CH_REASON IS 'Contract ch_reason in BSCS'
/

COMMENT ON COLUMN IBP_STAGING.TIMESTAMP IS 'Timestamp of request insertion'
/

COMMENT ON COLUMN IBP_STAGING.REQ_ID IS 'Unique sequence number'
/

COMMENT ON COLUMN IBP_STAGING.CO_ID IS 'BSCS Contract ID'
/

COMMENT ON COLUMN IBP_STAGING.CUSTOMER_ID IS 'Customer ID'
/

COMMENT ON COLUMN IBP_STAGING.SEQ IS 'BSCS Sequence of the request'
/

COMMENT ON COLUMN IBP_STAGING.TMCODE IS 'Tmcodes'
/

COMMENT ON COLUMN IBP_STAGING.SNCODE IS 'Sncodes'
/

COMMENT ON COLUMN IBP_STAGING.OLD_VAL IS 'Old value of the corresponding request in BSCS'
/

COMMENT ON COLUMN IBP_STAGING.NEW_VAL IS 'New value of the request in BSCS'
/

COMMENT ON COLUMN IBP_STAGING.ACTION_ID IS 'IBP Action Id'
/


Prompt Index IBP_STAGING_PK;
--
-- IBP_STAGING_PK  (Index) 
--
--  Dependencies: 
--   IBP_STAGING (Table)
--
CREATE UNIQUE INDEX IBP_STAGING_PK ON IBP_STAGING (REQ_ID) LOGGING TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table IBP_STAGING 
-- 
Prompt Non-Foreign Key Constraints on Table IBP_STAGING;
ALTER TABLE IBP_STAGING ADD (  CONSTRAINT CHECK_REQUEST_STATUS CHECK (REQUEST_STATUS in ( 'NULL', 'U', 'P', 'IA', 'IB','E', 'E-No data')),  CONSTRAINT IBP_STAGING_PK PRIMARY KEY (REQ_ID) USING INDEX TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ))
/

-- 
-- Foreign Key Constraints for Table IBP_STAGING 
-- 
Prompt Foreign Key Constraints on Table IBP_STAGING;
ALTER TABLE IBP_STAGING ADD (  FOREIGN KEY (ACTION_ID) REFERENCES IBP_BSCS_ACTIONS (ACTION_ID) ON DELETE CASCADE)
/




Prompt Table IBP_PROCESSING_QUEUE;
--
-- IBP_PROCESSING_QUEUE  (Table) 
--
--  Dependencies: 
--   IBP_BSCS_ACTIONS (Table)
--   IBP_STAGING (Table)
--
CREATE TABLE IBP_PROCESSING_QUEUE ( ID NUMBER NOT NULL, CUSTOMER_ID NUMBER NOT NULL, BILLCYCLE VARCHAR2(2 CHAR), CH_REASON CHAR(1 CHAR), MSISDN VARCHAR2(20 CHAR), CO_ID NUMBER, TMCODE NUMBER, SNCODE NUMBER, SERVICEPARAMETER VARCHAR2(255 CHAR), OLD_VAL VARCHAR2(2000 CHAR), NEW_VAL VARCHAR2(2000 CHAR), ACTION_ID NUMBER NOT NULL, PROCESS_STATUS_TIMESTAMP DATE, PROCESS_STATUS NUMBER, REMARK LONG, SCCODE NUMBER, REQ_ID NUMBER NOT NULL, PORT_NUM VARCHAR2(50 CHAR) ) TABLESPACE DATA PCTUSED 0 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL NOMONITORING
/

COMMENT ON TABLE IBP_PROCESSING_QUEUE IS 'Input table to IBP'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.ID IS 'Sequence ID'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.CUSTOMER_ID IS 'Customer ID'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.BILLCYCLE IS 'BSCS Billcycle'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.CH_REASON IS 'BSCS contract CH_REASON'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.MSISDN IS 'BSCS MSISDN'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.CO_ID IS 'BSCS Contract Id'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.TMCODE IS 'Tmcode'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.SNCODE IS 'Sncode'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.SERVICEPARAMETER IS 'Service parameter change'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.OLD_VAL IS 'Old value of the corressponding IBP request parameter'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.NEW_VAL IS 'New value of Old value of the corressponding IBP request parameter'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.ACTION_ID IS 'IBP BSCS Actions'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.PROCESS_STATUS_TIMESTAMP IS 'Time when process status is updated'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.PROCESS_STATUS IS 'process status update by IBP core processor'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.REMARK IS 'To contain associated SNCODEs or MSISDNS'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.SCCODE IS 'BSCS sccode'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.REQ_ID IS 'IBP_STAGING request id'
/

COMMENT ON COLUMN IBP_PROCESSING_QUEUE.PORT_NUM IS 'Port number of IMSI'
/


Prompt Index IBP_PROCESSING_QUEUE_PK;
--
-- IBP_PROCESSING_QUEUE_PK  (Index) 
--
--  Dependencies: 
--   IBP_PROCESSING_QUEUE (Table)
--
CREATE UNIQUE INDEX IBP_PROCESSING_QUEUE_PK ON IBP_PROCESSING_QUEUE (ID) LOGGING TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table IBP_PROCESSING_QUEUE 
-- 
Prompt Non-Foreign Key Constraints on Table IBP_PROCESSING_QUEUE;
ALTER TABLE IBP_PROCESSING_QUEUE ADD (  CONSTRAINT CHECK_PROCESS_STATUS CHECK (PROCESS_STATUS in ( 0,1,2,10)), CONSTRAINT IBP_PROCESSING_QUEUE_PK PRIMARY KEY (ID) USING INDEX TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ))
/

-- -- Foreign Key Constraints for Table IBP_PROCESSING_QUEUE 
-- 
Prompt Foreign Key Constraints on Table IBP_PROCESSING_QUEUE;
ALTER TABLE IBP_PROCESSING_QUEUE ADD (  FOREIGN KEY (ACTION_ID) REFERENCES IBP_BSCS_ACTIONS (ACTION_ID),  FOREIGN KEY (REQ_ID) REFERENCES IBP_STAGING (REQ_ID) ON DELETE CASCADE)
/


Prompt Table IBP_ORDERLINE_MBC;
--
-- IBP_ORDERLINE_MBC  (Table) 
--
CREATE TABLE IBP_ORDERLINE_MBC ( REQUEST_ID NUMBER, ORDERLINE_OBJECT CLOB, CUSTOMER_ID NUMBER, MSISDN NUMBER, MSISDN_SEQUENCE NUMBER, ACTION_ID NUMBER NOT NULL, ORDERLINE_CREATION_TIMESTAMP DATE, PROCESS_TIME_STAMP DATE, APPLICATION_RETURN_CODE NUMBER, RETURN_CODE NUMBER, RETRY_NUMBER NUMBER ) TABLESPACE DATA PCTUSED 0 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) LOGGING NOCOMPRESS LOB (ORDERLINE_OBJECT) STORE AS ( TABLESPACE DATA ENABLE STORAGE IN ROW CHUNK 8192 RETENTION NOCACHE INDEX ( TABLESPACE DATA STORAGE ( INITIAL 64K NEXT 1 MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )) STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) ) NOCACHE NOPARALLEL NOMONITORING
/

COMMENT ON TABLE IBP_ORDERLINE_MBC IS 'Orderline Tables for MBC'
/

COMMENT ON COLUMN IBP_ORDERLINE_MBC.REQUEST_ID IS 'Unique sequence'
/

COMMENT ON COLUMN IBP_ORDERLINE_MBC.ORDERLINE_OBJECT IS 'CLOB xml value'
/

COMMENT ON COLUMN IBP_ORDERLINE_MBC.CUSTOMER_ID IS 'Customer ID'
/

COMMENT ON COLUMN IBP_ORDERLINE_MBC.MSISDN IS 'MSISDN number of contract'
/

COMMENT ON COLUMN IBP_ORDERLINE_MBC.MSISDN_SEQUENCE IS 'MSISDN sequence number'
/

COMMENT ON COLUMN IBP_ORDERLINE_MBC.ACTION_ID IS 'BSCS Actions ID referring to IBP_BSCS_ACTIONS.ACTION_ID'
/

COMMENT ON COLUMN IBP_ORDERLINE_MBC.ORDERLINE_CREATION_TIMESTAMP IS 'Order line creation timestamp'
/

COMMENT ON COLUMN IBP_ORDERLINE_MBC.PROCESS_TIME_STAMP IS 'Updated by ESB/MBC adapter when the request is picked up'
/

COMMENT ON COLUMN IBP_ORDERLINE_MBC.APPLICATION_RETURN_CODE IS 'Return code from MBC'
/

COMMENT ON COLUMN IBP_ORDERLINE_MBC.RETURN_CODE IS 'Return code added by MBC adapter'
/

COMMENT ON COLUMN IBP_ORDERLINE_MBC.RETRY_NUMBER IS 'Retry Number used to lock MBC rows'
/

Prompt Index IBP_ORDERLINE_MBC_PK;
--
-- IBP_ORDERLINE_MBC_PK  (Index) 
--
--  Dependencies: 
--   IBP_ORDERLINE_MBC (Table)
--
CREATE UNIQUE INDEX IBP_ORDERLINE_MBC_PK ON IBP_ORDERLINE_MBC (REQUEST_ID) LOGGING TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table IBP_ORDERLINE_MBC 
-- 
Prompt Non-Foreign Key Constraints on Table IBP_ORDERLINE_MBC;
ALTER TABLE IBP_ORDERLINE_MBC ADD (  CONSTRAINT CHECK_RETURN_CODE_VAL CHECK (RETURN_CODE IN (0,1,2,11,12)),  
CONSTRAINT IBP_ORDERLINE_MBC_PK PRIMARY KEY (REQUEST_ID) USING INDEX TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ))
/



Prompt Table IBP_ORDERLINE_MZ;
--
-- IBP_ORDERLINE_MZ  (Table) 
--
--  Dependencies: 
--   IBP_BSCS_ACTIONS (Table)
--
CREATE TABLE IBP_ORDERLINE_MZ ( REQUEST_ID NUMBER NOT NULL, ORDERLINE_OBJECT CLOB, CUSTOMER_ID NUMBER, MSISDN NUMBER, MSISDN_SEQUENCE NUMBER, ACTION_ID NUMBER NOT NULL, ORDERLINE_CREATION_TIMESTAMP DATE, PROCESS_TIME_STAMP DATE, APPLICATION_RETURN_CODE NUMBER, RETURN_CODE NUMBER, RETRY_NUMBER NUMBER ) TABLESPACE DATA PCTUSED 0 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) LOGGING NOCOMPRESS LOB (ORDERLINE_OBJECT) STORE AS ( TABLESPACE DATA ENABLE STORAGE IN ROW CHUNK 8192 RETENTION NOCACHE INDEX ( TABLESPACE DATA STORAGE ( INITIAL 64K NEXT 1 MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )) STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) ) NOCACHE NOPARALLEL NOMONITORING
/

COMMENT ON TABLE IBP_ORDERLINE_MBC IS 'Orderline Tables for MZ'
/

COMMENT ON COLUMN IBP_ORDERLINE_MZ.REQUEST_ID IS 'Unique sequence'
/

COMMENT ON COLUMN IBP_ORDERLINE_MZ.ORDERLINE_OBJECT IS 'CLOB xml value'
/

COMMENT ON COLUMN IBP_ORDERLINE_MZ.CUSTOMER_ID IS 'Customer ID'
/

COMMENT ON COLUMN IBP_ORDERLINE_MZ.MSISDN IS 'MSISDN number of contract'
/

COMMENT ON COLUMN IBP_ORDERLINE_MZ.MSISDN_SEQUENCE IS 'MSISDN sequence number'
/

COMMENT ON COLUMN IBP_ORDERLINE_MZ.ACTION_ID IS 'BSCS Actions ID referring to IBP_BSCS_ACTIONS.ACTION_ID'
/

COMMENT ON COLUMN IBP_ORDERLINE_MZ.ORDERLINE_CREATION_TIMESTAMP IS 'Order line creation timestamp'
/

COMMENT ON COLUMN IBP_ORDERLINE_MZ.PROCESS_TIME_STAMP IS 'Updated when the request is picked up for processing'
/

COMMENT ON COLUMN IBP_ORDERLINE_MZ.APPLICATION_RETURN_CODE IS 'Return code from NE'
/

COMMENT ON COLUMN IBP_ORDERLINE_MZ.RETURN_CODE IS 'Return code updated after the request processing'
/

COMMENT ON COLUMN IBP_ORDERLINE_MZ.RETRY_NUMBER IS 'Retry Number used to lock rows'
/


Prompt Index IBP_ORDERLINE_MZ_PK;
--
-- IBP_ORDERLINE_MZ_PK  (Index) 
--
--  Dependencies: 
--   IBP_ORDERLINE_MZ (Table)
--
CREATE UNIQUE INDEX IBP_ORDERLINE_MZ_PK ON IBP_ORDERLINE_MZ (REQUEST_ID) LOGGING TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table IBP_ORDERLINE_MZ 
-- 
Prompt Non-Foreign Key Constraints on Table IBP_ORDERLINE_MZ;
ALTER TABLE IBP_ORDERLINE_MZ ADD (  CONSTRAINT CHECK_RETURN_CODE_VAL_MZ CHECK (RETURN_CODE IN (0,1,2,11,12)),  
CONSTRAINT IBP_ORDERLINE_MZ_PK PRIMARY KEY (REQUEST_ID) USING INDEX TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ))
/

-- 
-- Foreign Key Constraints for Table IBP_ORDERLINE_MZ 
-- 
Prompt Foreign Key Constraints on Table IBP_ORDERLINE_MZ;
ALTER TABLE IBP_ORDERLINE_MZ ADD (  FOREIGN KEY (ACTION_ID) REFERENCES IBP_BSCS_ACTIONS (ACTION_ID) ON DELETE CASCADE)
/



Prompt Table IBP_ORDERLINE_PCRF;
--
-- IBP_ORDERLINE_PCRF  (Table) 
--
--  Dependencies: 
--   IBP_BSCS_ACTIONS (Table)
--
CREATE TABLE IBP_ORDERLINE_PCRF ( REQUEST_ID NUMBER NOT NULL, ORDERLINE_OBJECT CLOB, CUSTOMER_ID NUMBER, MSISDN NUMBER, MSISDN_SEQUENCE NUMBER, ACTION_ID NUMBER NOT NULL, ORDERLINE_CREATION_TIMESTAMP DATE, PROCESS_TIME_STAMP DATE, APPLICATION_RETURN_CODE NUMBER, RETURN_CODE NUMBER, RETRY_NUMBER NUMBER ) TABLESPACE DATA PCTUSED 0 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) LOGGING NOCOMPRESS LOB (ORDERLINE_OBJECT) STORE AS ( TABLESPACE DATA ENABLE STORAGE IN ROW CHUNK 8192 RETENTION NOCACHE INDEX ( TABLESPACE DATA STORAGE ( INITIAL 64K NEXT 1 MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )) STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) ) NOCACHE NOPARALLEL NOMONITORING
/

COMMENT ON TABLE IBP_ORDERLINE_MBC IS 'Orderline Tables for PCRF'
/

COMMENT ON COLUMN IBP_ORDERLINE_PCRF.REQUEST_ID IS 'Unique sequence'
/

COMMENT ON COLUMN IBP_ORDERLINE_PCRF.ORDERLINE_OBJECT IS 'CLOB xml value'
/

COMMENT ON COLUMN IBP_ORDERLINE_PCRF.CUSTOMER_ID IS 'Customer ID'
/

COMMENT ON COLUMN IBP_ORDERLINE_PCRF.MSISDN IS 'MSISDN number of contract'
/

COMMENT ON COLUMN IBP_ORDERLINE_PCRF.MSISDN_SEQUENCE IS 'MSISDN sequence number'
/

COMMENT ON COLUMN IBP_ORDERLINE_PCRF.ACTION_ID IS 'BSCS Actions ID referring to IBP_BSCS_ACTIONS.ACTION_ID'
/

COMMENT ON COLUMN IBP_ORDERLINE_PCRF.ORDERLINE_CREATION_TIMESTAMP IS 'Order line creation timestamp'
/

COMMENT ON COLUMN IBP_ORDERLINE_PCRF.PROCESS_TIME_STAMP IS 'Updated adapter when the request is picked up for processing'
/

COMMENT ON COLUMN IBP_ORDERLINE_PCRF.APPLICATION_RETURN_CODE IS 'Return code from NE'
/

COMMENT ON COLUMN IBP_ORDERLINE_PCRF.RETURN_CODE IS 'Return code added after request processing'
/

COMMENT ON COLUMN IBP_ORDERLINE_PCRF.RETRY_NUMBER IS 'Retry Number used to lock rows'
/


Prompt Index IBP_ORDERLINE_PCRF_PK;
--
-- IBP_ORDERLINE_PCRF_PK  (Index) 
--
--  Dependencies: 
--   IBP_ORDERLINE_PCRF (Table)
--
CREATE UNIQUE INDEX IBP_ORDERLINE_PCRF_PK ON IBP_ORDERLINE_PCRF (REQUEST_ID) LOGGING TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) NOPARALLEL
/

-- 
-- Non Foreign Key Constraints for Table IBP_ORDERLINE_PCRF 
-- 
Prompt Non-Foreign Key Constraints on Table IBP_ORDERLINE_PCRF;
ALTER TABLE IBP_ORDERLINE_PCRF ADD (  CONSTRAINT CHECK_RETURN_CODE_VAL_PCRF CHECK (RETURN_CODE IN (0,1,2,11,12)),  CONSTRAINT IBP_ORDERLINE_PCRF_PK PRIMARY KEY (REQUEST_ID) USING INDEX TABLESPACE DATA PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ))
/

-- 
-- Foreign Key Constraints for Table IBP_ORDERLINE_PCRF 
-- 
Prompt Foreign Key Constraints on Table IBP_ORDERLINE_PCRF;
ALTER TABLE IBP_ORDERLINE_PCRF ADD (  FOREIGN KEY (ACTION_ID) REFERENCES IBP_BSCS_ACTIONS (ACTION_ID) ON DELETE CASCADE)
/



---------------------------------------------------------------------------------------------------------
--           4. Create DB links
---------------------------------------------------------------------------------------------------------

Prompt drop DB Link &&TO_BSCS_DB;
DROP DATABASE LINK &&TO_BSCS_DB
/

Prompt Database Link &&TO_BSCS_DB;


CREATE DATABASE LINK &&TO_BSCS_DB
 CONNECT TO &&USER
 IDENTIFIED BY &&PWD
 USING '&&DBNAME'
/

---------------------------------------------------------------------------------------------------------
----- 5. Create IBP Package
---------------------------------------------------------------------------------------------------------


Prompt drop Package IBP;
DROP PACKAGE IBP
/

Prompt drop Package Body IBP;
DROP PACKAGE BODY IBP
/

Prompt Package IBP;
--
-- IBP  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE PACKAGE IBP AS
   PROCEDURE ibp_contract_activation (i_req_id IN INTEGER);
   PROCEDURE ibp_service_activation (i_req_id IN INTEGER);
   PROCEDURE ibp_service_deactivation (i_req_id IN INTEGER);
   PROCEDURE ibp_contract_sus_react_deact (i_req_id IN INTEGER);
   PROCEDURE ibp_rateplan_change (i_req_id IN INTEGER);
   PROCEDURE ibp_parameter_change (i_req_id IN INTEGER);
   PROCEDURE ibp_billcycle_change (i_req_id IN INTEGER);
   PROCEDURE ibp_msisdn_change (i_req_id IN INTEGER);
   PROCEDURE ibp_imsi_change (i_req_id IN INTEGER);
   PROCEDURE ibp_contract_takeover (i_req_id IN INTEGER);
   PROCEDURE ibp_process_queue_population (i_req_id IN INTEGER);
END IBP;
/

SHOW ERRORS;



Prompt Package Body IBP;
--
-- IBP  (Package Body) 
--
CREATE OR REPLACE PACKAGE BODY IBP AS
   PROCEDURE ibp_contract_activation (i_req_id IN INTEGER)
   IS
      v_co_id       INTEGER;
      v_imsi        VARCHAR2 (50);
      v_sccode      INTEGER;
      v_action_id   NUMBER;
      v_ch_reason   INTEGER;
      v_cust_id     INTEGER;
      v_msisdn      VARCHAR2 (20);
      v_bcycle      VARCHAR2 (2);
      v_tm          INTEGER;
      v_rem         LONG;
   BEGIN
      SELECT   co_id, ch_reason, action_id
        INTO   v_co_id, v_ch_reason, v_action_id
        FROM   ibp_staging
       WHERE   req_id = i_req_id AND action_id = 1;

      SELECT   customer_id,
               billcycle,
               dn_num,
               tmcode,
               sccode,
               cd_port_num
        INTO   v_cust_id,
               v_bcycle,
               v_msisdn,
               v_tm,
               v_sccode,
               v_imsi
        FROM   ibp_view@&&TO_BSCS_DB
       WHERE   co_id = v_co_id;

      FOR i
      IN (SELECT   sncode
                   || NVL2 (cs_sparam1, '(' || cs_sparam1 || ')', NULL)
                      serv
            FROM   contr_services@&&TO_BSCS_DB
           WHERE       co_id = v_co_id
                   AND SUBSTR (cs_stat_chng, -1) = 'a'
                   AND tmcode = v_tm
                   AND sncode IN (SELECT   sncode
                                    FROM   ibp_product_configuration
                                   WHERE   tmcode = v_tm OR tmcode = '*'))
      LOOP
         v_rem := v_rem || i.serv || '|';
      END LOOP;

      v_rem := v_rem || '::';

      FOR j
      IN (SELECT   dn_num
            FROM   ibp_view@&&TO_BSCS_DB
           WHERE       customer_id = v_cust_id
                   AND ch_status IN ('a', 's')
                   AND sccode = v_sccode
                   AND dn_num != v_msisdn)
      LOOP
         v_rem := v_rem || '|' || j.dn_num;
      END LOOP;

      INSERT INTO ibp_processing_queue (id,
                                        customer_id,
                                        billcycle,
                                        ch_reason,
                                        msisdn,
                                        co_id,
                                        tmcode,
                                        action_id,
                                        process_status_timestamp,
                                        process_status,
                                        sccode,
                                        remark,
                                        req_id,
                                        port_num)
        VALUES   (IBP_PROCESSING_SEQ.NEXTVAL,
                  v_cust_id,
                  v_bcycle,
                  v_ch_reason,
                  v_msisdn,
                  v_co_id,
                  v_tm,
                  v_action_id,
                  SYSDATE,
                  0,
                  v_sccode,
                  v_rem,
                  i_req_id,
                  v_imsi);

      UPDATE   ibp_staging
         SET   request_status = 'P'
       WHERE   req_id = i_req_id;

      COMMIT;
   EXCEPTION
      WHEN NO_DATA_FOUND
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E-No data'
          WHERE   req_id = i_req_id;

         COMMIT;
      WHEN OTHERS
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E'
          WHERE   req_id = i_req_id;

         COMMIT;
   END;

   PROCEDURE ibp_service_activation (i_req_id IN INTEGER)
   IS
      v_co_id       INTEGER;
      v_action_id   NUMBER;
      v_imsi        VARCHAR2 (50);
      v_sn          INTEGER;
      v_sccode      INTEGER;
      v_cust_id     INTEGER;
      v_msisdn      VARCHAR2 (20);
      v_cs_param1   VARCHAR2 (2000);
      v_tm          INTEGER;
      v_rem         LONG;
      v_cnt         NUMBER;
      v_bcycle      VARCHAR2 (2);
   BEGIN
      SELECT   co_id,
               tmcode,
               sncode,
               cs_param1,
               action_id
        INTO   v_co_id,
               v_tm,
               v_sn,
               v_cs_param1,
               v_action_id
        FROM   ibp_staging
       WHERE   req_id = i_req_id AND action_id = 5; -- retriving information generated by trigger

      SELECT   COUNT (1)
        INTO   v_cnt
        FROM   ibp_product_configuration
       WHERE   tmcode IN (v_tm, '*') AND sncode = v_sn; -- checking whether the service is releate to IBP or not

      IF (v_cnt > 0)
      THEN
         SELECT   customer_id,
                  dn_num,
                  sccode,
                  cd_port_num,
                  billcycle
           INTO   v_cust_id,
                  v_msisdn,
                  v_sccode,
                  v_imsi,
                  v_bcycle
           FROM   ibp_view@&&TO_BSCS_DB
          WHERE   co_id = v_co_id;

         FOR j
         IN (SELECT   dn_num
               FROM   ibp_view@&&TO_BSCS_DB
              WHERE       customer_id = v_cust_id
                      AND ch_status IN ('a', 's')
                      AND sccode = v_sccode
                      AND dn_num != v_msisdn)
         LOOP
            v_rem := v_rem || j.dn_num || '|';
         END LOOP;

         v_rem := SUBSTR (v_rem, 1, LENGTH (v_rem) - 1);

         INSERT INTO ibp_processing_queue (id,
                                           customer_id,
                                           billcycle,
                                           msisdn,
                                           co_id,
                                           tmcode,
                                           sncode,
                                           serviceparameter,
                                           action_id,
                                           process_status_timestamp,
                                           process_status,
                                           remark,
                                           req_id,
                                           port_num)
           VALUES   (IBP_PROCESSING_SEQ.NEXTVAL,
                     v_cust_id,
                     v_bcycle,
                     v_msisdn,
                     v_co_id,
                     v_tm,
                     v_sn,
                     v_cs_param1,
                     v_action_id,
                     SYSDATE,
                     0,
                     v_rem,
                     i_req_id,
                     v_imsi);

         UPDATE   ibp_staging
            SET   request_status = 'P'
          WHERE   req_id = i_req_id;

         COMMIT;
      ELSE
         UPDATE   ibp_staging
            SET   request_status = 'IB'
          WHERE   req_id = i_req_id;

         COMMIT;
      END IF;
   EXCEPTION
      WHEN NO_DATA_FOUND
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E-No data'
          WHERE   req_id = i_req_id;

         COMMIT;
      WHEN OTHERS
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E'
          WHERE   req_id = i_req_id;

         COMMIT;
   END;

   PROCEDURE ibp_service_deactivation (i_req_id IN INTEGER)
   IS
      v_co_id       INTEGER;
      v_imsi        VARCHAR2 (50);
      v_action_id   NUMBER;
      v_sn          INTEGER;
      v_cust_id     INTEGER;
      v_msisdn      VARCHAR2 (20);
      v_cs_param1   VARCHAR2 (2000);
      v_tm          INTEGER;
      v_cnt         NUMBER;
      v_sccode      INTEGER;
      v_bcycle      VARCHAR (2);
   BEGIN
      SELECT   co_id,
               tmcode,
               sncode,
               cs_param1,
               action_id
        INTO   v_co_id,
               v_tm,
               v_sn,
               v_cs_param1,
               v_action_id
        FROM   ibp_staging
       WHERE   req_id = i_req_id AND action_id = 6;

      SELECT   COUNT (1)
        INTO   v_cnt
        FROM   ibp_staging
       WHERE       co_id = v_co_id
               AND action_id = 12
               AND req_id > i_req_id
               AND old_val = v_tm;

      IF (v_cnt > 0)
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'IA'
          WHERE   req_id = i_req_id;

         COMMIT;
      ELSE
         SELECT   COUNT (1)
           INTO   v_cnt
           FROM   ibp_product_configuration
          WHERE   tmcode IN (v_tm, '*') AND sncode = v_sn;

         IF (v_cnt > 0)
         THEN
            SELECT   customer_id,
                     dn_num,
                     sccode,
                     cd_port_num,
                     billcycle
              INTO   v_cust_id,
                     v_msisdn,
                     v_sccode,
                     v_imsi,
                     v_bcycle
              FROM   ibp_view@&&TO_BSCS_DB
             WHERE   co_id = v_co_id;

            INSERT INTO ibp_processing_queue (id,
                                              customer_id,
					      billcycle,
                                              msisdn,
                                              co_id,
                                              tmcode,
                                              sncode,
                                              serviceparameter,
                                              action_id,
                                              process_status_timestamp,
                                              process_status,
                                              req_id,
                                              port_num)
              VALUES   (IBP_PROCESSING_SEQ.NEXTVAL,
                        v_cust_id,
                        v_bcycle,
                        v_msisdn,
                        v_co_id,
                        v_tm,
                        v_sn,
                        v_cs_param1,
                        v_action_id,
                        SYSDATE,
                        0,
                        i_req_id,
                        v_imsi);

            UPDATE   ibp_staging
               SET   request_status = 'P'
             WHERE   req_id = i_req_id;

            COMMIT;
         ELSE
            UPDATE   ibp_staging
               SET   request_status = 'IB'
             WHERE   req_id = i_req_id;

            COMMIT;
         END IF;
      END IF;
   EXCEPTION
      WHEN NO_DATA_FOUND
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E-No data'
          WHERE   req_id = i_req_id;

         COMMIT;
      WHEN OTHERS
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E'
          WHERE   req_id = i_req_id;

         COMMIT;
   END;

   PROCEDURE ibp_contract_sus_react_deact (i_req_id IN INTEGER)
   IS
      v_co_id       INTEGER;
      v_imsi        VARCHAR2 (50);
      v_action_id   NUMBER;
      v_ch_reason   INTEGER;
      v_cust_id     INTEGER;
      v_tm          INTEGER;
      v_msisdn      VARCHAR2 (20);
      v_rem         LONG;
      v_sccode      INTEGER;
   BEGIN
      SELECT   co_id, ch_reason, action_id
        INTO   v_co_id, v_ch_reason, v_action_id
        FROM   ibp_staging
       WHERE   req_id = i_req_id AND action_id IN (2, 3, 4);

      SELECT   customer_id,
               dn_num,
               sccode,
               cd_port_num,
               tmcode
        INTO   v_cust_id,
               v_msisdn,
               v_sccode,
               v_imsi,
               v_tm
        FROM   ibp_view@&&TO_BSCS_DB
       WHERE   co_id = v_co_id;

      IF (v_action_id = 2)
      THEN
         FOR i
         IN (SELECT   sncode
                      || NVL2 (cs_sparam1, '(' || cs_sparam1 || ')', NULL)
                         serv
               FROM   contr_services@&&TO_BSCS_DB
              WHERE   co_id = v_co_id
                      AND SUBSTR (cs_stat_chng, -7) =
                            TO_CHAR (SYSDATE, 'yymmdd') || 'd'
                      AND tmcode = v_tm
                      AND sncode IN
                               (SELECT   sncode
                                  FROM   ibp_product_configuration
                                 WHERE   tmcode = v_tm OR tmcode = '*'))
         LOOP
            v_rem := v_rem || i.serv || '|';
         END LOOP;

         v_rem := SUBSTR (v_rem, 1, LENGTH (v_rem) - 1);
      END IF;

      INSERT INTO ibp_processing_queue (id,
                                        customer_id,
                                        msisdn,
                                        co_id,
                                        action_id,
                                        ch_reason,
                                        process_status_timestamp,
                                        process_status,
                                        req_id,
                                        port_num,
                                        remark)
        VALUES   (IBP_PROCESSING_SEQ.NEXTVAL,
                  v_cust_id,
                  v_msisdn,
                  v_co_id,
                  v_action_id,
                  v_ch_reason,
                  SYSDATE,
                  0,
                  i_req_id,
                  v_imsi,
                  v_rem);

      UPDATE   ibp_staging
         SET   request_status = 'P'
       WHERE   req_id = i_req_id;

      COMMIT;
   EXCEPTION
      WHEN NO_DATA_FOUND
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E-No data'
          WHERE   req_id = i_req_id;

         COMMIT;
      WHEN OTHERS
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E'
          WHERE   req_id = i_req_id;

         COMMIT;
   END;

   PROCEDURE ibp_rateplan_change (i_req_id IN INTEGER)
   IS
      v_co_id       INTEGER;
      v_action_id   NUMBER;
      v_imsi        VARCHAR2 (50);
      v_old_tm      NUMBER;
      v_new_tm      NUMBER;
      v_cust_id     INTEGER;
      v_msisdn      VARCHAR2 (20);
      v_sccode      INTEGER;
      v_bcycle      VARCHAR2 (10);
      v_tm          INTEGER;
      v_rem         LONG;
   BEGIN
      SELECT   co_id,
               old_val,
               new_val,
               action_id
        INTO   v_co_id,
               v_old_tm,
               v_new_tm,
               v_action_id
        FROM   ibp_staging
       WHERE   req_id = i_req_id AND action_id = 12;

      UPDATE   ibp_staging
         SET   request_status = 'IA'
       WHERE       co_id = v_co_id
               AND action_id = 6
               AND req_id < i_req_id
               AND request_status IS NULL;

      COMMIT;

      SELECT   customer_id,
               billcycle,
               dn_num,
               tmcode,
               sccode,
               cd_port_num
        INTO   v_cust_id,
               v_bcycle,
               v_msisdn,
               v_tm,
               v_sccode,
               v_imsi
        FROM   ibp_view@&&TO_BSCS_DB
       WHERE   co_id = v_co_id;

      FOR i
      IN (SELECT   sncode
                   || NVL2 (cs_sparam1, '(' || cs_sparam1 || ')', NULL)
                      serv
            FROM   contr_services@&&TO_BSCS_DB
           WHERE       co_id = v_co_id
                   AND SUBSTR (cs_stat_chng, -1) = 'a'
                   AND tmcode = v_tm
                   AND sncode IN (SELECT   sncode
                                    FROM   ibp_product_configuration
                                   WHERE   tmcode = v_tm OR tmcode = '*')
                   AND cs_seqno = (SELECT   MAX (cs_seqno)
                                     FROM   contr_services@&&TO_BSCS_DB
                                    WHERE   co_id = v_co_id))
      LOOP
         v_rem := v_rem || i.serv || '|';
      END LOOP;

      v_rem := v_rem || '::';

      FOR j
      IN (SELECT   dn_num
            FROM   ibp_view@&&TO_BSCS_DB
           WHERE       customer_id = v_cust_id
                   AND ch_status IN ('a', 's')
                   AND sccode = v_sccode
                   AND dn_num != v_msisdn)
      LOOP
         v_rem := v_rem || '|' || j.dn_num;
      END LOOP;

      INSERT INTO ibp_processing_queue (id,
                                        customer_id,
                                        billcycle,
                                        old_val,
                                        new_val,
                                        msisdn,
                                        co_id,
                                        tmcode,
                                        action_id,
                                        process_status_timestamp,
                                        process_status,
                                        sccode,
                                        remark,
                                        req_id,
                                        port_num)
        VALUES   (IBP_PROCESSING_SEQ.NEXTVAL,
                  v_cust_id,
                  v_bcycle,
                  v_old_tm,
                  v_new_tm,
                  v_msisdn,
                  v_co_id,
                  v_tm,
                  v_action_id,
                  SYSDATE,
                  0,
                  v_sccode,
                  v_rem,
                  i_req_id,
                  v_imsi);

      UPDATE   ibp_staging
         SET   request_status = 'P'
       WHERE   req_id = i_req_id;

      COMMIT;
   EXCEPTION
      WHEN NO_DATA_FOUND
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E-No data'
          WHERE   req_id = i_req_id;

         COMMIT;
      WHEN OTHERS
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E'
          WHERE   req_id = i_req_id;

         COMMIT;
   END;

   PROCEDURE ibp_parameter_change (i_req_id IN INTEGER)
   IS
      v_co_id       INTEGER;
      v_action_id   NUMBER;
      v_sn          INTEGER;
      v_imsi        VARCHAR2 (50);
      v_sccode      INTEGER;
      v_cust_id     INTEGER;
      v_msisdn      VARCHAR2 (20);
      v_cs_param1   VARCHAR2 (2000);
      v_tm          INTEGER;
      v_old_param   VARCHAR2 (2000);
      v_new_param   VARCHAR2 (2000);
      v_cnt         NUMBER;
   BEGIN
      SELECT   co_id,
               tmcode,
               sncode,
               cs_param1,
               old_val,
               new_val,
               action_id
        INTO   v_co_id,
               v_tm,
               v_sn,
               v_cs_param1,
               v_old_param,
               v_new_param,
               v_action_id
        FROM   ibp_staging
       WHERE   req_id = i_req_id AND action_id = 7;

      SELECT   COUNT (1)
        INTO   v_cnt
        FROM   ibp_product_configuration
       WHERE   tmcode IN (v_tm, '*') AND sncode = v_sn;

      IF (v_cnt > 0)
      THEN
         SELECT   customer_id,
                  dn_num,
                  sccode,
                  cd_port_num
           INTO   v_cust_id,
                  v_msisdn,
                  v_sccode,
                  v_imsi
           FROM   ibp_view@&&TO_BSCS_DB
          WHERE   co_id = v_co_id;

         INSERT INTO ibp_processing_queue (id,
                                           customer_id,
                                           msisdn,
                                           co_id,
                                           tmcode,
                                           sncode,
                                           serviceparameter,
                                           old_val,
                                           new_val,
                                           action_id,
                                           process_status_timestamp,
                                           process_status,
                                           req_id,
                                           port_num)
           VALUES   (IBP_PROCESSING_SEQ.NEXTVAL,
                     v_cust_id,
                     v_msisdn,
                     v_co_id,
                     v_tm,
                     v_sn,
                     v_cs_param1,
                     v_old_param,
                     v_new_param,
                     v_action_id,
                     SYSDATE,
                     0,
                     i_req_id,
                     v_imsi);

         UPDATE   ibp_staging
            SET   request_status = 'P'
          WHERE   req_id = i_req_id;

         COMMIT;
      ELSE
         UPDATE   ibp_staging
            SET   request_status = 'IB'
          WHERE   req_id = i_req_id;

         COMMIT;
      END IF;
   EXCEPTION
      WHEN NO_DATA_FOUND
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E-No data'
          WHERE   req_id = i_req_id;

         COMMIT;
      WHEN OTHERS
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E'
          WHERE   req_id = i_req_id;

         COMMIT;
   END;

   PROCEDURE ibp_billcycle_change (i_req_id IN INTEGER)
   IS
      v_cust_id         INTEGER;
      v_action_id       NUMBER;
      v_old_billcycle   VARCHAR2 (2);
      v_new_billcycle   VARCHAR2 (2);
      v_rem             LONG;
   BEGIN
      SELECT   customer_id,
               old_val,
               new_val,
               action_id
        INTO   v_cust_id,
               v_old_billcycle,
               v_new_billcycle,
               v_action_id
        FROM   ibp_staging
       WHERE   req_id = i_req_id AND action_id = 10;

      FOR j IN (SELECT   dn_num
                  FROM   ibp_view@&&TO_BSCS_DB
                 WHERE   customer_id = v_cust_id AND ch_status IN ('a', 's'))
      LOOP
         v_rem := v_rem || '|' || j.dn_num;
      END LOOP;

      v_rem := SUBSTR (v_rem, 2);

      INSERT INTO ibp_processing_queue (id,
                                        customer_id,
                                        billcycle,
                                        old_val,
                                        new_val,
                                        action_id,
                                        process_status_timestamp,
                                        process_status,
                                        remark,
                                        req_id)
        VALUES   (IBP_PROCESSING_SEQ.NEXTVAL,
                  v_cust_id,
                  v_new_billcycle,
                  v_old_billcycle,
                  v_new_billcycle,
                  v_action_id,
                  SYSDATE,
                  0,
                  v_rem,
                  i_req_id);

      UPDATE   ibp_staging
         SET   request_status = 'P'
       WHERE   req_id = i_req_id;

      COMMIT;
   EXCEPTION
      WHEN NO_DATA_FOUND
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E-No data'
          WHERE   req_id = i_req_id;

         COMMIT;
      WHEN OTHERS
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E'
          WHERE   req_id = i_req_id;

         COMMIT;
   END;

   PROCEDURE ibp_msisdn_change (i_req_id IN INTEGER)
   IS
      v_co_id        INTEGER;
      v_cust_id      INTEGER;
      v_imsi         VARCHAR2 (50);
      v_action_id    NUMBER;
      v_old_id       NUMBER;
      v_new_id       NUMBER;
      v_old_msisdn   VARCHAR2 (20);
      v_new_msisdn   VARCHAR2 (20);
   BEGIN
      SELECT   co_id,
               old_val,
               new_val,
               action_id
        INTO   v_co_id,
               v_old_id,
               v_new_id,
               v_action_id
        FROM   ibp_staging
       WHERE   req_id = i_req_id AND action_id = 9;

      SELECT   customer_id, cd_port_num
        INTO   v_cust_id, v_imsi
        FROM   ibp_view@&&TO_BSCS_DB
       WHERE   co_id = v_co_id;

      SELECT   dn_num
        INTO   v_old_msisdn
        FROM   directory_number@&&TO_BSCS_DB
       WHERE   dn_id = v_old_id;

      SELECT   dn_num
        INTO   v_new_msisdn
        FROM   directory_number@&&TO_BSCS_DB
       WHERE   dn_id = v_new_id;

      INSERT INTO ibp_processing_queue (id,
                                        customer_id,
                                        co_id,
                                        msisdn,
                                        old_val,
                                        new_val,
                                        action_id,
                                        process_status_timestamp,
                                        process_status,
                                        req_id,
                                        port_num)
        VALUES   (IBP_PROCESSING_SEQ.NEXTVAL,
                  v_cust_id,
                  v_co_id,
                  v_new_msisdn,
                  v_old_msisdn,
                  v_new_msisdn,
                  v_action_id,
                  SYSDATE,
                  0,
                  i_req_id,
                  v_imsi);

      UPDATE   ibp_staging
         SET   request_status = 'P'
       WHERE   req_id = i_req_id;

      COMMIT;
   EXCEPTION
      WHEN NO_DATA_FOUND
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E-No data'
          WHERE   req_id = i_req_id;

         COMMIT;
      WHEN OTHERS
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E'
          WHERE   req_id = i_req_id;

         COMMIT;
   END;

   PROCEDURE ibp_imsi_change (i_req_id IN INTEGER)
   IS
      v_co_id       INTEGER;
      v_action_id   NUMBER;
      v_cust_id     INTEGER;
      v_imsi        VARCHAR2 (50);
      v_msisdn      VARCHAR2 (20);
      v_old_imsi    VARCHAR2 (50);
      v_new_imsi    VARCHAR2 (50);
   BEGIN
      SELECT   co_id,
               old_val,
               new_val,
               action_id
        INTO   v_co_id,
               v_old_imsi,
               v_new_imsi,
               v_action_id
        FROM   ibp_staging
       WHERE   req_id = i_req_id AND action_id = 8;

      SELECT   customer_id, dn_num, cd_port_num
        INTO   v_cust_id, v_msisdn, v_imsi
        FROM   ibp_view@&&TO_BSCS_DB
       WHERE   co_id = v_co_id;

      INSERT INTO ibp_processing_queue (id,
                                        co_id,
                                        customer_id,
                                        msisdn,
                                        old_val,
                                        new_val,
                                        action_id,
                                        process_status_timestamp,
                                        process_status,
                                        req_id,
                                        port_num)
        VALUES   (IBP_PROCESSING_SEQ.NEXTVAL,
                  v_co_id,
                  v_cust_id,
                  v_msisdn,
                  v_old_imsi,
                  v_new_imsi,
                  v_action_id,
                  SYSDATE,
                  0,
                  i_req_id,
                  v_imsi);

      UPDATE   ibp_staging
         SET   request_status = 'P'
       WHERE   req_id = i_req_id;

      COMMIT;
   EXCEPTION
      WHEN NO_DATA_FOUND
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E-No data'
          WHERE   req_id = i_req_id;

         COMMIT;
      WHEN OTHERS
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E'
          WHERE   req_id = i_req_id;

         COMMIT;
   END;

   PROCEDURE ibp_contract_takeover (i_req_id IN INTEGER)
   IS
      v_co_id       INTEGER;
      v_sccode      INTEGER;
      v_imsi        VARCHAR2 (50);
      v_action_id   NUMBER;
      v_old_co_id   NUMBER;
      v_new_co_id   NUMBER;
      v_ch_reason   INTEGER;
      v_cust_id     INTEGER;
      v_msisdn      NUMBER;
      v_bcycle      VARCHAR2 (10);
      v_tm          INTEGER;
      v_rem         LONG;
   BEGIN
      SELECT   co_id,
               old_val,
               new_val,
               action_id
        INTO   v_co_id,
               v_old_co_id,
               v_new_co_id,
               v_action_id
        FROM   ibp_staging
       WHERE   req_id = i_req_id AND action_id = 11;

      SELECT   customer_id,
               billcycle,
               dn_num,
               tmcode,
               sccode,
               cd_port_num
        INTO   v_cust_id,
               v_bcycle,
               v_msisdn,
               v_tm,
               v_sccode,
               v_imsi
        FROM   ibp_view@&&TO_BSCS_DB
       WHERE   co_id = v_co_id;

      FOR i
      IN (SELECT   sncode
                   || NVL2 (cs_sparam1, '(' || cs_sparam1 || ')', NULL)
                      serv
            FROM   contr_services@&&TO_BSCS_DB
           WHERE       co_id = v_co_id
                   AND tmcode = v_tm
                   AND sncode IN (SELECT   sncode
                                    FROM   ibp_product_configuration
                                   WHERE   tmcode = v_tm OR tmcode = '*'))
      LOOP
         v_rem := v_rem || i.serv || '|';
      END LOOP;

      v_rem := v_rem || '::';

      FOR j
      IN (SELECT   dn_num
            FROM   ibp_view@&&TO_BSCS_DB
           WHERE       customer_id = v_cust_id
                   AND ch_status IN ('a', 's')
                   AND sccode = v_sccode
                   AND dn_num != v_msisdn)
      LOOP
         v_rem := v_rem || '|' || j.dn_num;
      END LOOP;

      SELECT   customer_id
        INTO   v_old_co_id
        FROM   contract_all@&&TO_BSCS_DB
       WHERE   co_id = v_old_co_id;

      SELECT   customer_id
        INTO   v_new_co_id
        FROM   contract_all@&&TO_BSCS_DB
       WHERE   co_id = v_new_co_id;

      INSERT INTO ibp_processing_queue (id,
                                        customer_id,
                                        billcycle,
                                        ch_reason,
                                        msisdn,
                                        co_id,
                                        tmcode,
                                        action_id,
                                        old_val,
                                        new_val,
                                        process_status_timestamp,
                                        process_status,
                                        sccode,
                                        remark,
                                        req_id,
                                        port_num)
        VALUES   (IBP_PROCESSING_SEQ.NEXTVAL,
                  v_cust_id,
                  v_bcycle,
                  v_ch_reason,
                  v_msisdn,
                  v_co_id,
                  v_tm,
                  v_action_id,
                  v_old_co_id,
                  v_new_co_id,
                  SYSDATE,
                  0,
                  v_sccode,
                  v_rem,
                  i_req_id,
                  v_imsi);

      UPDATE   ibp_staging
         SET   request_status = 'P'
       WHERE   req_id = i_req_id;

      COMMIT;
   EXCEPTION
      WHEN NO_DATA_FOUND
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E-No data'
          WHERE   req_id = i_req_id;

         COMMIT;
      WHEN OTHERS
      THEN
         UPDATE   ibp_staging
            SET   request_status = 'E'
          WHERE   req_id = i_req_id;

         COMMIT;
   END;

   PROCEDURE ibp_process_queue_population (i_req_id IN INTEGER)
   IS
      v_action_id   NUMBER;
   BEGIN
      SELECT   action_id
        INTO   v_action_id
        FROM   ibp_staging
       WHERE   req_id = i_req_id;

      CASE v_action_id
         WHEN 1
         THEN
            ibp.ibp_contract_activation (i_req_id);
         WHEN 2
         THEN
            ibp.ibp_contract_sus_react_deact (i_req_id);
         WHEN 3
         THEN
            ibp.ibp_contract_sus_react_deact (i_req_id);
         WHEN 4
         THEN
            ibp.ibp_contract_sus_react_deact (i_req_id);
         WHEN 5
         THEN
            ibp.ibp_service_activation (i_req_id);
         WHEN 6
         THEN
            ibp.ibp_service_deactivation (i_req_id);
         WHEN 7
         THEN
            ibp.ibp_parameter_change (i_req_id);
         WHEN 8
         THEN
            ibp.ibp_imsi_change (i_req_id);
         WHEN 9
         THEN
            ibp.ibp_msisdn_change (i_req_id);
         WHEN 10
         THEN
            ibp.ibp_billcycle_change (i_req_id);
         WHEN 11
         THEN
            ibp.ibp_contract_takeover (i_req_id);
         WHEN 12
         THEN
            ibp.ibp_rateplan_change (i_req_id);
         ELSE
            UPDATE   ibp_staging
               SET   request_status = 'E'
             WHERE   req_id = i_req_id;
      END CASE;
   END;
END ibp;
/

SHOW ERRORS;

---------------------------------------------------------------------------------------------------------
----- 5. Create IBP Procedures e.g Archiving procs, update orderline commands
---------------------------------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE IBP_UPDATE_ORDERLINE_XML
( REQ_ID IN INTEGER,
  XMLTAG IN VARCHAR2,
  XMLVAL IN VARCHAR2,    
  TABLE_NAME IN VARCHAR2,
  RESULT  OUT INTEGER ) 
  IS
 
  SQL_QUERY VARCHAR2(2000) := NULL;
  SQL_STMT VARCHAR2(2000) := NULL;
BEGIN
  SQL_QUERY := 'UPDATE ' || TABLE_NAME || ' SET ORDERLINE_OBJECT = updateXML(XMLTYPE.createXML(ORDERLINE_OBJECT),' ||
  XMLTAG || ',' || XMLVAL || ').getClobVal() WHERE REQUEST_ID = ' || REQ_ID ;
  
  EXECUTE IMMEDIATE SQL_QUERY; 
  
  COMMIT;
  
  RESULT:= 1;
EXCEPTION
      WHEN OTHERS
      THEN
         RESULT := -1;
END;
/


---------------------------------------------------------------------------------------------------------
----- 7. INSERTION INTO IBP_BSCS_ACTIONS and IBP_PRODUCT_TYPE_DEFINITION
--------------------------------------------------------------------------------------------------------

PROMPT insert into IBP_BSCS_ACTIONS;

SET SERVEROUTPUT ON;

BEGIN
INSERT ALL 
INTO IBP_BSCS_ACTIONS( ACTION_ID, BSCS_ACTION_NAME) VALUES ( 1, 'CONTRACT_ACTIVATION')
INTO IBP_BSCS_ACTIONS( ACTION_ID, BSCS_ACTION_NAME) VALUES ( 2, 'CONTRACT_DEACTIVATION')
INTO IBP_BSCS_ACTIONS( ACTION_ID, BSCS_ACTION_NAME) VALUES ( 3, 'CONTRACT_SUSPENSION')
INTO IBP_BSCS_ACTIONS( ACTION_ID, BSCS_ACTION_NAME) VALUES ( 4, 'CONTRACT_REACTIVATION')
INTO IBP_BSCS_ACTIONS( ACTION_ID, BSCS_ACTION_NAME) VALUES ( 5, 'SERVICE_ACTIVATION')
INTO IBP_BSCS_ACTIONS( ACTION_ID, BSCS_ACTION_NAME) VALUES ( 6, 'SERVICE_DEACTIVATION')
INTO IBP_BSCS_ACTIONS( ACTION_ID, BSCS_ACTION_NAME) VALUES ( 7, 'SERVICE_PARAM_CHANGE')
INTO IBP_BSCS_ACTIONS( ACTION_ID, BSCS_ACTION_NAME) VALUES ( 8, 'IMSI_CHANGE')
INTO IBP_BSCS_ACTIONS( ACTION_ID, BSCS_ACTION_NAME) VALUES ( 9, 'MSISDN_CHANGE')
INTO IBP_BSCS_ACTIONS( ACTION_ID, BSCS_ACTION_NAME) VALUES ( 10, 'BILL_CYCLE_CHANGE')
INTO IBP_BSCS_ACTIONS( ACTION_ID, BSCS_ACTION_NAME) VALUES ( 11, 'CONTRACT_TAKEOVER')
INTO IBP_BSCS_ACTIONS( ACTION_ID, BSCS_ACTION_NAME) VALUES ( 12, 'RATE_PLAN_CHANGE')
SELECT * FROM DUAL;

commit;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE( 'ERROR CODE: '||SQLCODE || 'And ERROR TEXT: ' || SUBSTR( SQLERRM,1,64));
rollback;
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE || 'And ERROR TEXT: ' || SUBSTR( SQLERRM,1,64));
rollback;
End;
/



PROMPT insert into IBP_PRODUCT_TYPE_DEFINITION;

BEGIN
INSERT ALL 
INTO IBP_PRODUCT_TYPE_DEFINITION( PRODUCT_TYPE_ID, PRODUCT_TYPE, PARAMETER_TRANSLATION ) VALUES ( 1, 'FULLY_SHARED', 'N')
INTO IBP_PRODUCT_TYPE_DEFINITION( PRODUCT_TYPE_ID, PRODUCT_TYPE, PARAMETER_TRANSLATION ) VALUES ( 2, 'PARTIALLY_SHARED_IMPL', 'N')
INTO IBP_PRODUCT_TYPE_DEFINITION( PRODUCT_TYPE_ID, PRODUCT_TYPE, PARAMETER_TRANSLATION ) VALUES ( 3, 'PARTIALLY_SHARED_EXPL', 'N')
INTO IBP_PRODUCT_TYPE_DEFINITION( PRODUCT_TYPE_ID, PRODUCT_TYPE, PARAMETER_TRANSLATION ) VALUES ( 4, 'MONOLITHIC', 'N')
INTO IBP_PRODUCT_TYPE_DEFINITION( PRODUCT_TYPE_ID, PRODUCT_TYPE, PARAMETER_TRANSLATION ) VALUES ( 5, 'SUM_N_SHARE', 'N')
INTO IBP_PRODUCT_TYPE_DEFINITION( PRODUCT_TYPE_ID, PRODUCT_TYPE, PARAMETER_TRANSLATION ) VALUES ( 6, 'PCRF_PROFILE_CHANGE', 'N')
INTO IBP_PRODUCT_TYPE_DEFINITION( PRODUCT_TYPE_ID, PRODUCT_TYPE, PARAMETER_TRANSLATION ) VALUES ( 7, 'MZ_PROFILE_CHANGE', 'N')
INTO IBP_PRODUCT_TYPE_DEFINITION( PRODUCT_TYPE_ID, PRODUCT_TYPE, PARAMETER_TRANSLATION ) VALUES ( 8, 'SERVICE_LIMIT', 'N')
INTO IBP_PRODUCT_TYPE_DEFINITION( PRODUCT_TYPE_ID, PRODUCT_TYPE, PARAMETER_TRANSLATION ) VALUES ( 9, 'DEFAULT_OFFER', 'N')
INTO IBP_PRODUCT_TYPE_DEFINITION( PRODUCT_TYPE_ID, PRODUCT_TYPE, PARAMETER_TRANSLATION ) VALUES ( 10, 'NON_GSM', 'N')

SELECT * FROM DUAL;

commit;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE( 'ERROR CODE: '||SQLCODE || 'And ERROR TEXT: ' || SUBSTR( SQLERRM,1,64));
rollback;
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE || 'And ERROR TEXT: ' || SUBSTR( SQLERRM,1,64));
rollback;
End;
/



